name: Branch Protection Enforcement

on:
  push:
    branches: [ main, master ]

jobs:
  enforce-pr-only:
    name: Enforce PR-Only Access
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !startsWith(github.ref, 'refs/heads/dependabot/') && github.actor != 'github-actions[bot]'
    
    steps:
    - name: Check if push is from PR merge
      uses: actions/github-script@v7
      with:
        script: |
          const { data: commits } = await github.rest.repos.listCommits({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            per_page: 1
          });
          
          const commit = commits[0];
          const isMergeCommit = commit.parents.length > 1;
          const commitMessage = commit.commit.message;
          
          // Check if this is a merge commit from a PR
          const isPRMerge = isMergeCommit && (
            commitMessage.includes('Merge pull request #') ||
            commitMessage.includes('Squashed commit')
          );
          
          if (!isPRMerge) {
            // This appears to be a direct push, not a PR merge
            core.setFailed(`
            ❌ DIRECT PUSH DETECTED TO PROTECTED BRANCH!
            
            Branch: ${context.ref}
            Actor: ${context.actor}
            Commit: ${context.sha}
            
            🚫 Direct pushes to ${context.ref.replace('refs/heads/', '')} are not allowed.
            📋 All changes must go through a Pull Request.
            
            Please:
            1. Create a feature branch
            2. Make your changes there  
            3. Create a Pull Request
            4. Wait for review and CI checks
            5. Merge through the PR process
            
            If this was an emergency hotfix, please create a PR afterward to document the change.
            `);
          } else {
            console.log('✅ Valid PR merge detected');
          }

  notify-direct-push:
    name: Notify Direct Push Attempt
    runs-on: ubuntu-latest
    needs: enforce-pr-only
    if: failure()
    
    steps:
    - name: Create issue for direct push
      uses: actions/github-script@v7
      with:
        script: |
          const title = `🚨 Direct Push Alert: Unauthorized push to ${context.ref.replace('refs/heads/', '')}`;
          const body = `
          ## 🚨 Branch Protection Violation
          
          A direct push was detected to the protected branch \`${context.ref.replace('refs/heads/', '')}\`.
          
          **Details:**
          - **Actor:** @${context.actor}
          - **Branch:** ${context.ref.replace('refs/heads/', '')}
          - **Commit:** ${context.sha}
          - **Time:** ${new Date().toISOString()}
          
          **Required Actions:**
          1. ✅ Review the changes made
          2. ✅ Ensure branch protection rules are properly configured
          3. ✅ Create a follow-up PR if needed for documentation
          4. ✅ Remind team members about PR-only workflow
          
          **Branch Protection Rules:**
          - All changes must go through Pull Requests
          - PR must have at least 1 approval
          - All CI checks must pass
          - No force pushes allowed
          
          This issue was created automatically by the branch protection enforcement workflow.
          `;
          
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: title,
            body: body,
            labels: ['security', 'branch-protection', 'urgent']
          });
          
          console.log('Issue created for direct push violation');
