name: Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 2 * * 1' # Run every Monday at 2 AM

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  security-scan:
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore AQ.sln
    
    - name: Run security audit
      run: dotnet list package --vulnerable --include-transitive
    
    - name: Install dotnet-outdated
      run: dotnet tool install -g dotnet-outdated-tool
    
    - name: Check for outdated packages
      run: dotnet outdated --include-transitive
      continue-on-error: true
